---
title: "Example application using openEnded to analyze open-ended manipulation checks"
author: "Jeffrey Ziegler"
date: "`r Sys.Date()`"
output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{Example Application}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Installation

```{r, eval=FALSE}
# install and load package
devtools::install_github('jeffreyziegler/openEnded', force=T, build_vignettes=T)
library(openEnded)
```

```{r, echo=FALSE, messages=F}
# load package
library(openEnded)
```

## Example Application: Ziegler (2020)

```{r}
# load data from GitHub
replication_complete.cases <- read.csv("http://bit.ly/repData", 
                                       stringsAsFactors = F)
# re-level factors
replication_complete.cases$Concordant <- relevel(as.factor(replication_complete.cases$Concordant), ref = "0")
replication_complete.cases$attendanceBin <- relevel(as.factor(replication_complete.cases$attendanceBin), ref = "Never/yearly")
```

Create similarity measures.

```{r}
# create jaccard and cosine similarity measures
replication_complete.cases <- similarityMeasures(dataframe=replication_complete.cases, 
                           similarity_measures_to_calculate=c("jaccard", "cosine", "jw", "dl"), 
                           prompt="textViewed", response="validityCheck", ngrams=3)
```

```{r, fig.show=TRUE, fig.height=6, fig.width=7, align="center", warning=F, message=F}
# plot Jaccard distances for just Brazil
brazil_rows <- which(replication_complete.cases$Country=="Brazil")
plotSimilarity(dataframe=replication_complete.cases[brazil_rows,],
               measure="jaccardDist", xlab="Jaccard Similarity")
```